name: control_center
description: "My personal control center application"
publish_to: 'none'
version: 1.6.1+16

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  everything_i_need:
    git:
      url: https://github.com/channdara/everything_i_need.git
      ref: main
  app_settings: ^7.0.0
  google_fonts: ^8.1.0
  screen_brightness: ^2.1.7
  shared_preferences: ^2.5.5
  flutter_volume_controller: ^1.3.4
  material_symbols_icons: ^4.2928.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true